name: Validate PR on Develop

on:
  pull_request:
    branches: 
      - develop

jobs:
  backend-build:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-rest/
         
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn test

  frontend-build:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    strategy:
       matrix:
         node-version: [16.x, 18.x, 20.x]
    
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-angular/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          #node-version: 20.9.0
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './00-spring-petclinic-deployment/spring-petclinic-angular/package-lock.json'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present -- --configuration production
      - name: Test
        run: npm run test-headless
