name: Validate PR on Develop

on:
  pull_request:
    branches: 
      - develop

jobs:
  backend-build:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd 00-spring-petclinic-deployment/spring-petclinic-rest/ 
          mvn verify

  frontend-build:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        #with: 
          #path: 00-spring-petclinic-deployment/spring-petclinic-angular/
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0
          cache: 'npm'
          cache-dependency-path: './00-spring-petclinic-deployment/spring-petclinic-angular/package-lock.json'
      - name: Install Dependencies
        run: | 
          cd 00-spring-petclinic-deployment/spring-petclinic-angular/ 
          npm ci
      - name: Build
        run: npm run build --if-present -- --configuration production
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test-headless
