name: Build and Push Docker Images on Develop Merge

on:
  pull_request:
    types: closed
    branches: 
      - develop

jobs:
  backend-build-and-deploy:
    if: github.event.pull_request.merged == true
    name: Backend Build and Test
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-rest/
         
    steps:
      - name: Check out repository     
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn verify

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          #logout: # optional, default is true

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/petclinic-rest:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/petclinic-rest:latest

  frontend-build:
    if: github.event.pull_request.merged == true
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-angular/

    steps:
      - name: Check out repository       
        uses: actions/checkout@v4
        
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: 'npm'
          cache-dependency-path: './00-spring-petclinic-deployment/spring-petclinic-angular/package-lock.json'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build --prod
        
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          #logout: # optional, default is true

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/petclinic-angular:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/petclinic-angular:latest
