name: Build and Push Docker Images on Develop Merge

on:
  pull_request:
    types: closed
    branches: 
      - develop

jobs:
  backend:
    if: github.event.pull_request.merged == true
    name: Backend Build and Deploy
    runs-on: self-hosted
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-rest/
      
    steps:
      - name: Check out repository     
        uses: actions/checkout@v4

      - name: Git Short Commit SHA Extraction
        id: sha_step
        run: export sha_short=$(git rev-parse --short HEAD)
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./00-spring-petclinic-deployment/spring-petclinic-rest/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-rest:${{ steps.sha_step.outputs.sha_short }}
            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-rest:latest

  frontend:
    if: github.event.pull_request.merged == true
    name: Frontend Build and Deploy
    needs: backend
    runs-on: self-hosted
    defaults:
       run:
         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-angular/

    steps: 
      - name: Check out repository       
        uses: actions/checkout@v4

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./00-spring-petclinic-deployment/spring-petclinic-angular/
          push: true
          tags: | 
            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-angular:$sha_short
            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-angular:latest
    
  docker-compose:
    name: Docker Compose
    needs: frontend
    runs-on: self-hosted

    steps:
      - name: Check out repository       
        uses: actions/checkout@v4

      - name: Docker Compose
        run: docker compose -f ./00-spring-petclinic-deployment/docker-compose.yml up -d

      #- name: Docker Compose Action
        #uses: isbang/compose-action@v1.5.1
        #with:
          #compose-file: "./00-spring-petclinic-deployment/docker-compose.yml"

#name: Build and Push Docker Images on Develop Merge
#
#on:
#  pull_request:
#    types: closed
#    branches: 
#      - develop
#
#jobs:
#  backend:
#    if: github.event.pull_request.merged == true
#    name: Backend Build and Deploy
#    runs-on: self-hosted
#    defaults:
#       run:
#         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-rest/
#    outputs:
#      sha_short: ${{ steps.sha_step.outputs.sha_short }}
#      
#    steps:
#      - name: Check out repository     
#        uses: actions/checkout@v4
#
#      - name: Git Short Commit SHA Extraction
#        id: sha_step
#        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          
#      - name: Build and push Docker images
#        uses: docker/build-push-action@v5
#        with:
#          context: ./00-spring-petclinic-deployment/spring-petclinic-rest/
#          push: true
#          tags: |
#            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-rest:${{ steps.sha_step.outputs.sha_short }}
#            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-rest:latest
#
#  frontend:
#    if: github.event.pull_request.merged == true
#    name: Frontend Build and Deploy
#    needs: backend
#    runs-on: self-hosted
#    defaults:
#       run:
#         working-directory: ./00-spring-petclinic-deployment/spring-petclinic-angular/
#
#    steps: 
#      - name: Check out repository       
#        uses: actions/checkout@v4
#
#      - name: Build and push Docker images
#        uses: docker/build-push-action@v5
#        with:
#          context: ./00-spring-petclinic-deployment/spring-petclinic-angular/
#          push: true
#          tags: | 
#            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-angular:${{ needs.backend.outputs.sha_short }}
#            ${{ secrets.DOCKER_USERNAME }}/spring-petclinic-angular:latest
#    
#  docker-compose:
#    name: Docker Compose
#    needs: frontend
#    runs-on: self-hosted
#
#    steps:
#      - name: Check out repository       
#        uses: actions/checkout@v4
#
#      - name: Docker Compose
#        run: docker compose -f ./00-spring-petclinic-deployment/docker-compose.yml up -d
#
#      #- name: Docker Compose Action
#        #uses: isbang/compose-action@v1.5.1
#        #with:
#          #compose-file: "./00-spring-petclinic-deployment/docker-compose.yml"
